---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tonyblair-app
  namespace: monitoring
  labels:
    app: tonyblair-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tonyblair-app
  template:
    metadata:
      labels:
        app: tonyblair-app
    spec:
      containers:
        - name: tonyblair-app
          image: tonyblair/app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"